@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "123456"
}

###

# @name create_delivery
POST {{baseUrl}}/deliveries
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "itemName": "Computer"
}

###

# @name fetch_customer_deliveries
GET {{baseUrl}}/deliveries
Content-Type: application/json
Authorization: Bearer {{authToken}}
